version: '3'

services:
  mysql-transfer:
    container_name: mysql-transfer
    image: "mysql:8.0.33"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: transfer_google_drive
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    external: true
