version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-123456}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME:-transfer_google_drive}
      MYSQL_USER: ${MYSQL_USERNAME:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    external: true
